import swaggerAutogen from "swagger-autogen"
import path from "path"

const outputFile = path.join(__dirname, "..", "..", "docs", "swagger_output.json")
const endpointsFiles = [path.join(__dirname, "..", "server.ts")]

const doc = {
    info: {
        version: "1.0.0",
        title: "Topindo API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        User: {
            id: 1,
            username: 'admin',
            password: 'admin',
            name: 'test',
            address: 'Bandung',
            age: 25,
            phoneNumber: '081234567890'
        }
    }
}

// @ts-ignore: Unreachable code error
swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
    await import("../router")
})